version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_instance
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: your_app_image:latest  # Replace with your app's Docker image
    container_name: app_instance
    ports:
      - "3000:3000"  # Replace with your app's port
    environment:
      - MONGO_URI=mongodb://mongo:27017/your_database  # Replace with your database name
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
