version: "3.8"

# This compose file is for development purposes
# I'm using render for deployment
# so i don't a compose.prod for this project
# i needed this file to spin up containers for my app in development

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: jobify-dev:latest
    container_name: app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
